### PR TITLE
quantumcode.py 2.part

### PR DESCRIPTION
**Pull request by zbpetersbuf**
Completed mapping classical inputs to a quantum problem and optimize it for a quantum computer I think, have yet to test in code space to see if functions properly

### CODE REVIEW

**Comment by laserlab** [comment]
Ah I see now what you meant. Yes that is fine too for finishing you homework task! So we can leave step 2 for someone else.

**Review by laserlab — CHANGES_REQUESTED** [review]
Before I merge this, can you add some inline comments to your code?

**Comment by zbpetersbuf** [comment]
I thought that what SchrodingersStruggle was doing?

**Comment by zbpetersbuf** [comment]
I can do it I just thought that's what SchrodingersStruggle meant, could of course be wrong though

**Comment by laserlab** [comment]
> I can do it I just thought that's what SchrodingersStruggle meant, could of course be wrong though

Sure let’s check with @SchrodingersStruggle

**Comment by laserlab** [comment]
Btw. @zbpetersbuf if you add a @ in front of a github username they get a notification.

**Comment by laserlab** [comment]
@zbpetersbuf I just noticed that you made a pull request from your main branch. While this still works, in the future you will get less homework points for that. You can leave it for now.

**Comment by SchrodingersStruggle** [comment]
> > I can do it I just thought that's what SchrodingersStruggle meant, could of course be wrong though
> 
> 
> 
> Sure let’s check with @SchrodingersStruggle 

Yes, that is what I was going to do. I have stepped away for a second but I still have every intention on completing it. For the in-line contributions, would I create my own pull request so that it actually contributes to my hw?

**Comment by laserlab** [comment]
> > > I can do it I just thought that's what SchrodingersStruggle meant, could of course be wrong though
> > 
> > 
> > Sure let’s check with @SchrodingersStruggle
> 
> Yes, that is what I was going to do. I have stepped away for a second but I still have every intention on completing it. For the in-line contributions, would I create my own pull request so that it actually contributes to my hw?

Yes. I will merge this then and you pick up from the merged files.

**Pull request merged**
