### PR TITLE
On the issue of the missing important imports

### PR DESCRIPTION
**Pull request by HeshamElsaman**
Added the needed imports for our code to be functional

### CODE REVIEW

**Comment by laserlab** [comment]
Not merging since this is already done here #31, please open a separate PR that uses that file and to update the current version.

**Comment by HeshamElsaman** [comment]
I really don't know how I got passed that. Apologies for that.
I will compare my files and merge then open a new pull request.

**Comment by HeshamElsaman** [comment]
@laserlab I'm currently checking it again and I find no conflicts between my repo and the main one, there might have been some mistake that removed the setup section because I can't find it in the up-to-date main repo right now.
So, I guess my pull request is good to go.

**Comment by laserlab** [comment]
check https://github.com/ubsuny/CP1-24-HW1/blob/e07b8b6451a69aecb1a814398b8b6b821ac6d310/Python/quantumcode.py

**Comment by HeshamElsaman** [comment]
@laserlab aren't we supposed to be checking this instead?
https://github.com/ubsuny/CP1-24-HW1/blob/main/bells-inequality/quantumcode.py

that's what in the up-to-date main repo at
https://github.com/ubsuny/CP1-24-HW1

I guess the link you attached is before the accident of deleting the file, or it's not?
Because I see no other pull requests that added any edits to the file afterwards.

**Comment by laserlab** [comment]
yes, exactly. Since you started the issue with the missing import I said they were in the deleted file which I linked

**Comment by HeshamElsaman** [comment]
@laserlab  I guess I'm lost now :"(
I don't quite get it
I will not be able to use the deleted file anyway, right?

**Comment by HeshamElsaman** [comment]
I added my edits based on the up-to-date repo

**Comment by laserlab** [comment]
The issue originally was that it needs the setup code. I answered that this was already done in the linked PR and to add from that file to a new PR.

**Pull request closed without merging**
