### PR TITLE
Unit testing branch, with restored /python directory

### PR DESCRIPTION
**Pull request by avgagliardo**
I was working on quantumcode.py and I noticed it disappeared. Not sure if this was intention (it doesn't seem like it was) so I've restored the directory and its file.

I've also made some changes to comments and added several TODO tasks.

### CODE REVIEW

**Comment by jkblc** [comment]
Good catch. This pull request is important!

**Comment by avgagliardo** [comment]
Updated main project dir names to be more self-descriptive.

**Comment by laserlab** [comment]
must have been in the lecture example and I didn’t catch it. I keep it in your Bell directory for now though it would be good to reorganize (@iamtomato761)

**Comment by iamtomato761** [comment]
> must have been in the lecture example and I didn’t catch it. I keep it in your Bell directory for now though it would be good to reorganize (@iamtomato761)

working on it

**Pull request merged**
