### PR TITLE
quantumcode.py

### PR DESCRIPTION
**Pull request by zbpetersbuf**
started first quantum code that maps classical to quantum, (beginnings)

### CODE REVIEW

**Review by laserlab — COMMENTED** [review]
This looks awesome. Could you add some inline comment what each code line does?

**Comment by zbpetersbuf** [comment]
Will do

**Comment by laserlab** [comment]
add a a label and a milestone to your PR please

**Comment by SchrodingersStruggle** [comment]
Hello @zbpetersbuf , do you mind if I assist in this task while opening my own pull request? Some things such as specifying the observables hasn't been covered yet.

**Comment by laserlab** [comment]
@zbpetersbuf Are you done? THen I can merge and it is easier for @SchrodingersStruggle to work on it too

**Comment by zbpetersbuf** [comment]
I am not done but I can finish it soon? or what do you mean? should I not complete this so you can work on it for your bit or should I finish it so you can do what you want to do?

**Comment by zbpetersbuf** [comment]
because Im ok with what ever and can finish it soon if that's what you need me to do

**Comment by laserlab** [comment]
I think it’s useful to merge at this point and add more content to another Pull Request. Since for your homework you going to need 2 PRs anyway. So I’m going to merge now. Thanks for getting this done!

**Comment by laserlab** [comment]
> Hello @zbpetersbuf , do you mind if I assist in this task while opening my own pull request? Some things such as specifying the observables hasn't been covered yet.

You can start from the merged files and add from there. Don’t forget to sync your fork from the repo.

**Comment by SchrodingersStruggle** [comment]
Okay, sounds good. Would it make sense to open us a new issue labeled to do or something of the sorts to work on organizing the task distribution?

**Comment by zbpetersbuf** [comment]
Ya I can make the new issue labeled task distribution, because I legitimately don't know what's happening anymore, my plan was to finish just coping the code with little messages describing what each line meant but im done now? like do I not continue doing that and you complete that? or do I still need to complete that cause im ok with anything I just don't know what's happening anymore

**Comment by zbpetersbuf** [comment]
I was also planing on getting it all into the codespace and to make sure the code was functioning properly hopefully before noon today but I stopped before that cause I was confused on the messages, and I don't want to do too much but I also don't know how much someone is suppose to do, I don't want to slack off and not do my share and make other people do more but I don't want to not leave stuff for others to do

**Comment by SchrodingersStruggle** [comment]
> Ya I can make the new issue labeled task distribution, because I legitimately don't know what's happening anymore, my plan was to finish just coping the code with little messages describing what each line meant but im done now? like do I not continue doing that and you complete that? or do I still need to complete that cause im ok with anything I just don't know what's happening anymore

Hey I just saw this, I already have an issue for it fired up, we can talk more in there!

**Comment by zbpetersbuf** [comment]
o I also just made one

**Pull request merged**
